agents:
  predators:
    count: 1
    base_type: predator
    speed: 1
    stamina: 100

  preys:
    count: 1
    base_type: prey
    speed: 1
    stamina: 100

  naming:
    predator_prefix: predator
    prey_prefix: prey
